# Generated by Django 3.1 on 2020-09-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='profile',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
